- name: Execute Docker Compose operations on remote host
  hosts: all
  become: yes

  vars:
    venv_path: /root/ansible_venv

  tasks:
    - name: Update package cache
      community.general.apk:
        update_cache: yes

    - name: Install required system packages
      community.general.apk:
        name:
          - python3
          - py3-pip
          - py3-virtualenv
          - docker-cli
          - py3-yaml
        state: present

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv {{ venv_path }}
        creates: "{{ venv_path }}"

    - name: Upgrade pip in virtual environment
      ansible.builtin.pip:
        name: pip
        state: latest
        virtualenv: "{{ venv_path }}"

    - name: Install PyYAML in virtual environment
      ansible.builtin.pip:
        name: PyYAML
        virtualenv: "{{ venv_path }}"
        state: present

    - name: Install docker and docker-compose modules in virtual environment
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose<2.0.0
        virtualenv: "{{ venv_path }}"
        state: present

    - name: Stop and remove containers
      community.docker.docker_compose:
        project_src: /root
        state: absent
      environment:
        PYTHONPATH: "{{ venv_path }}/lib/python3.12/site-packages:$PYTHONPATH"

    - name: Remove OpenVAS log file
      ansible.builtin.file:
        path: /var/lib/docker/volumes/root_openvas_log_data_vol/_data/openvas.log
        state: absent

    - name: Pull latest Docker images
      community.docker.docker_compose:
        project_src: /root
        pull: yes
      environment:
        PYTHONPATH: "{{ venv_path }}/lib/python3.12/site-packages:$PYTHONPATH"

    - name: Start Docker Compose services
      community.docker.docker_compose:
        project_src: /root
        state: present
      environment:
        PYTHONPATH: "{{ venv_path }}/lib/python3.12/site-packages:$PYTHONPATH"

    - name: Prune Docker images
      community.docker.docker_prune:
        images: yes
        images_filters:
          dangling: false
      environment:
        PYTHONPATH: "{{ venv_path }}/lib/python3.12/site-packages:$PYTHONPATH"
