---
- name: Execute Docker Compose operations on remote host
  hosts: all
  become: yes

  tasks:
    - name: Stop and remove containers
      ansible.builtin.command:
        cmd: docker compose -f /root/docker-compose.yml down
      ignore_errors: yes

    - name: Remove OpenVAS log file
      ansible.builtin.file:
        path: /var/lib/docker/volumes/root_openvas_log_data_vol/_data/openvas.log
        state: absent

    - name: Pull latest Docker images
      ansible.builtin.command:
        cmd: docker compose -f /root/docker-compose.yml pull

    - name: Start Docker Compose services
      ansible.builtin.command:
        cmd: docker compose -f /root/docker-compose.yml up -d

    - name: Prune Docker images
      ansible.builtin.command:
        cmd: docker image prune -f
