- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Ansible apt to install multiple packages
      register: updatesys
      apt:
        update_cache: yes
        name:
          - snmp
          - libsasl2-modules
          - qemu-guest-agent
        state: present
        
    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Ansible apt autoremove packages
      apt:
        autoremove: yes