- hosts: all
  name: "Play 1: 在所有 Alpine 主機上執行更新並收集狀態"
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: 執行更新並定義主機狀態
      block:
        - name: 更新 APK 套件庫索引
          ansible.builtin.apk:
            update_cache: yes
        
        - name: 升級所有已安裝的套件
          ansible.builtin.apk:
            upgrade: yes

        # 如果上面兩個任務都成功，設定狀態為 success
        - name: 設定主機狀態為 'success'
          ansible.builtin.set_fact:
            host_status: 'success'
      
      rescue:
        # 如果 block 中有任何任務失敗，設定狀態為 failed
        - name: 設定主機狀態為 'failed'
          ansible.builtin.set_fact:
            host_status: 'failed'
      
      # ignore_unreachable: yes 會讓無法連線的主機跳過 block/rescue
      # 我們會在 Play 2 中處理這些主機
      ignore_unreachable: yes
      ignore_errors: yes

- hosts: localhost
  name: "Play 2: 彙總結果並發送 Discord 通知"
  connection: local
  gather_facts: no
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
  
  tasks:
    - name: 彙總所有主機的執行狀態
      run_once: true
      ansible.builtin.set_fact:
        all_hosts_status: |
          {% set results = {'success': [], 'failed': [], 'unreachable': []} %}
          {% for host in groups['all'] %}
            {% set host_vars = hostvars[host] %}
            {% if host_vars.host_status is defined and host_vars.host_status == 'success' %}
              {% set _ = results.success.append(host) %}
            {% elif host_vars.host_status is defined and host_vars.host_status == 'failed' %}
              {% set _ = results.failed.append(host) %}
            {% else %}
              {% set _ = results.unreachable.append(host) %}
            {% endif %}
          {% endfor %}
          {{ results | to_json }} # <--- 關鍵修正：確保輸出為可解析的 JSON
          
    - name: 顯示狀態統計結果 (Debug)
      run_once: true
      ansible.builtin.debug:
        msg:
          - "總主機數: {{ groups['all'] | length }}"
          - "✅ 成功: {{ all_hosts_status.success | length }} 台 - {{ all_hosts_status.success | join(', ') }}"
          - "❌ 失敗: {{ all_hosts_status.failed | length }} 台 - {{ all_hosts_status.failed | join(', ') }}"
          - "❓ 無法連線: {{ all_hosts_status.unreachable | length }} 台 - {{ all_hosts_status.unreachable | join(', ') }}"

    - name: 準備失敗/無法連線主機的列表
      run_once: true
      ansible.builtin.set_fact:
        problem_hosts: "{{ all_hosts_status.failed + all_hosts_status.unreachable }}"

    - name: 當所有主機更新成功時，發送通知
      when: problem_hosts | length == 0
      run_once: true
      ansible.builtin.uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body:
          content: "✅ **Alpine 系統更新作業成功**"
          embeds:
            - title: "✅ 所有主機均已成功更新"
              description: "所有 **{{ groups['all'] | length }}** 台主機的 `apk upgrade` 已順利完成。"
              color: 3066993 # 綠色
              fields:
                - name: "成功主機"
                  value: "{{ all_hosts_status.success | length }} 台"
                  inline: true
                - name: "執行時間"
                  value: "{{ ansible_date_time.time }}"
                  inline: true
              timestamp: "{{ ansible_date_time.iso8601 }}"
        status_code: [200, 204]

    - name: 當有主機更新失敗或無法連線時，發送通知
      when: problem_hosts | length > 0
      run_once: true
      ansible.builtin.uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body:
          content: "❌ **Alpine 系統更新作業異常**"
          embeds:
            - title: "⚠️ 部分主機更新失敗或無法連線"
              description: "共 **{{ problem_hosts | length }}** 台主機需要注意。"
              color: 15158332 # 紅色
              fields:
                - name: "❌ 執行失敗 (Failed)"
                  value: |
                    {% if all_hosts_status.failed | length > 0 %}
                    {{ all_hosts_status.failed | join('\n') }}
                    {% else %}
                    無
                    {% endif %}
                  inline: false
                - name: "❓ 無法連線 (Unreachable)"
                  value: |
                    {% if all_hosts_status.unreachable | length > 0 %}
                    {{ all_hosts_status.unreachable | join('\n') }}
                    {% else %}
                    無
                    {% endif %}
                  inline: false
              timestamp: "{{ ansible_date_time.iso8601 }}"
        status_code: [200, 204]

    - name: 若有任何主機失敗，則將整個 Playbook 標記為失敗
      when: problem_hosts | length > 0
      run_once: true
      ansible.builtin.fail:
        msg: "共有 {{ problem_hosts | length }} 台主機更新失敗或無法連線：{{ problem_hosts | join(', ') }}"