- hosts: all
  become: yes
  become_user: root
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
  gather_facts: yes
  
  tasks:
    - name: Update apk repo and cache on all Alpine boxes
      apk: 
        update_cache: yes
      register: update_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Upgrade all packages on servers
      apk: 
        upgrade: yes
      register: upgrade_result
      ignore_unreachable: yes
      ignore_errors: yes

    # 判斷主機狀態
    - name: 判斷主機狀態
      set_fact:
        host_status: >-
          {% if update_result.unreachable | default(false) or upgrade_result.unreachable | default(false) %}unreachable{% elif update_result.failed | default(false) or upgrade_result.failed | default(false) %}failed{% else %}success{% endif %}

    # 記錄狀態（注意：使用 trim 移除空格）
    - name: 記錄主機狀態到檔案
      lineinfile:
        path: /tmp/ansible_run_status.txt
        line: "{{ ansible_date_time.iso8601 }}|{{ inventory_hostname }}|{{ host_status | trim }}"
        create: yes
      delegate_to: localhost
      become: no

- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
  
  roles:
    - role: update_notifier
      vars:
        notification_title: "Alpine"