- hosts: all
  become: yes
  become_user: root
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
    status_file: "{{ playbook_dir }}/.ansible_status/run_status.txt"
  gather_facts: yes
  
  tasks:
    # 確保狀態目錄存在
    - name: 確保狀態目錄存在
      file:
        path: "{{ playbook_dir }}/.ansible_status"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: no

    - name: Update apk repo and cache on all Alpine boxes
      apk:
        update_cache: yes
      register: update_result
      ignore_unreachable: yes
      failed_when: false

    - name: Upgrade all packages on servers
      apk:
        upgrade: yes
      register: upgrade_result
      ignore_unreachable: yes
      failed_when: false

    # 判斷主機狀態
    - name: 判斷主機狀態
      set_fact:
        host_status: >-
          {% if update_result.unreachable | default(false) or upgrade_result.unreachable | default(false) %}unreachable{% elif update_result.failed | default(false) or upgrade_result.failed | default(false) %}failed{% else %}success{% endif %}

    # 記錄狀態（使用 throttle 防止競態條件）
    - name: 記錄主機狀態到檔案
      lineinfile:
        path: "{{ status_file }}"
        line: "{{ ansible_date_time.iso8601 }}|{{ inventory_hostname }}|{{ host_status | trim }}"
        create: yes
      delegate_to: localhost
      become: no
      throttle: 1

- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
    status_file: "{{ playbook_dir }}/.ansible_status/run_status.txt"
    # 設定顯示時區，預設為 Asia/Taipei（台北時間 UTC+8）
    # 可透過 --extra-vars "display_timezone=Asia/Tokyo" 覆寫
    notification_timezone: "{{ display_timezone | default('Asia/Taipei') }}"
  
  roles:
    - role: update_notifier
      vars:
        notification_title: "Alpine"
        status_file_path: "{{ status_file }}"
        display_timezone: "{{ notification_timezone }}"