- hosts: all
  become: yes
  become_user: root
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
    status_file: "{{ playbook_dir }}/.ansible_status/run_status.txt"
  gather_facts: yes

  tasks:
    # 確保狀態目錄存在
    - name: 確保狀態目錄存在
      file:
        path: "{{ playbook_dir }}/.ansible_status"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: no

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      register: update_result
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      ignore_unreachable: yes
      failed_when: false

    - name: Ansible apt to install multiple packages
      register: install_result
      apt:
        update_cache: yes
        name:
          - snmp
          - libsasl2-modules
          - qemu-guest-agent
        state: present
      ignore_unreachable: yes
      failed_when: false
        
    - name: Upgrade all packages on servers
      register: upgrade_result
      apt:
        upgrade: dist
        force_apt_get: yes
      ignore_unreachable: yes
      failed_when: false

    - name: Ansible apt autoremove packages
      register: autoremove_result
      apt:
        autoremove: yes
      ignore_unreachable: yes
      failed_when: false
        
    # 判斷主機狀態
    - name: 判斷主機狀態
      set_fact:
        host_status: >-
          {% if update_result.unreachable | default(false) or
                install_result.unreachable | default(false) or
                upgrade_result.unreachable | default(false) or
                autoremove_result.unreachable | default(false) %}unreachable{% elif update_result.failed | default(false) or
                install_result.failed | default(false) or
                upgrade_result.failed | default(false) or
                autoremove_result.failed | default(false) %}failed{% else %}success{% endif %}
        has_updates: "{{ upgrade_result.changed | default(false) or install_result.changed | default(false) }}"

    # 記錄狀態
    - name: 記錄主機狀態到檔案
      lineinfile:
        path: "{{ status_file }}"
        line: "{{ ansible_date_time.iso8601 }}|{{ inventory_hostname }}|{{ host_status | trim }}|{{ has_updates }}"
        create: yes
      delegate_to: localhost
      become: no
      throttle: 1

- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
    status_file: "{{ playbook_dir }}/.ansible_status/run_status.txt"
  
  roles:
    - role: update_notifier
      vars:
        notification_title: "Proxmox"
        status_file_path: "{{ status_file }}"
        notification_timezone: "{{ display_timezone | default('Asia/Taipei') }}"