- hosts: all
  name: "Play 1: 在所有 Alpine 主機上執行更新"
  become: yes
  become_user: root
  gather_facts: no # 第一階段通常不需要 facts，可加速執行

  tasks:
    - name: 更新 APK 套件庫索引
      ansible.builtin.apk:
        update_cache: yes
      register: update_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: 升級所有已安裝的套件
      ansible.builtin.apk:
        upgrade: yes
      register: upgrade_result
      ignore_unreachable: yes
      ignore_errors: yes

- hosts: localhost
  name: "Play 2: 彙總結果並發送 Discord 通知"
  connection: local
  gather_facts: no # 此 Play 僅處理變數，不需要 facts
  vars:
    # 確保 discord_webhook_url 變數已定義 (可來自 inventory, extra-vars, etc.)
    discord_webhook: "{{ discord_webhook_url }}"
  
  tasks:
    - name: 彙總所有主機的執行狀態
      run_once: true
      ansible.builtin.set_fact:
        all_hosts_status: |
          {% set results = {'success': [], 'failed': [], 'unreachable': []} %}
          {% for host in groups['all'] %}
            {% set host_vars = hostvars[host] %}
            {% if host_vars.update_result is not defined or (host_vars.update_result.unreachable | default(false)) %}
              {% set _ = results.unreachable.append(host) %}
            {% elif (host_vars.update_result.failed | default(false)) or (host_vars.upgrade_result.failed | default(false)) %}
              {% set _ = results.failed.append(host) %}
            {% else %}
              {% set _ = results.success.append(host) %}
            {% endif %}
          {% endfor %}
          {{ results }}
          
    - name: 顯示狀態統計結果 (Debug)
      run_once: true
      ansible.builtin.debug:
        msg:
          - "總主機數: {{ groups['all'] | length }}"
          - "✅ 成功: {{ all_hosts_status.success | length }} 台 - {{ all_hosts_status.success | join(', ') }}"
          - "❌ 失敗: {{ all_hosts_status.failed | length }} 台 - {{ all_hosts_status.failed | join(', ') }}"
          - "❓ 無法連線: {{ all_hosts_status.unreachable | length }} 台 - {{ all_hosts_status.unreachable | join(', ') }}"

    - name: 準備失敗/無法連線主機的列表
      run_once: true
      ansible.builtin.set_fact:
        problem_hosts: "{{ all_hosts_status.failed + all_hosts_status.unreachable }}"

    - name: 當所有主機更新成功時，發送通知
      when: problem_hosts | length == 0
      run_once: true
      ansible.builtin.uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body:
          content: "✅ **Alpine 系統更新作業成功**"
          embeds:
            - title: "✅ 所有主機均已成功更新"
              description: "所有 **{{ groups['all'] | length }}** 台主機的 `apk upgrade` 已順利完成。"
              color: 3066993 # 綠色
              fields:
                - name: "成功主機"
                  value: "{{ all_hosts_status.success | length }} 台"
                  inline: true
                - name: "執行時間"
                  value: "{{ ansible_date_time.time }}"
                  inline: true
              timestamp: "{{ ansible_date_time.iso8601 }}"
        status_code: [200, 204]

    - name: 當有主機更新失敗或無法連線時，發送通知
      when: problem_hosts | length > 0
      run_once: true
      ansible.builtin.uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body:
          content: "❌ **Alpine 系統更新作業異常**"
          embeds:
            - title: "⚠️ 部分主機更新失敗或無法連線"
              description: "共 **{{ problem_hosts | length }}** 台主機需要注意。"
              color: 15158332 # 紅色
              fields:
                - name: "❌ 執行失敗 (Failed)"
                  value: |
                    {% if all_hosts_status.failed | length > 0 %}
                    {{ all_hosts_status.failed | join('\n') }}
                    {% else %}
                    無
                    {% endif %}
                  inline: false
                - name: "❓ 無法連線 (Unreachable)"
                  value: |
                    {% if all_hosts_status.unreachable | length > 0 %}
                    {{ all_hosts_status.unreachable | join('\n') }}
                    {% else %}
                    無
                    {% endif %}
                  inline: false
              timestamp: "{{ ansible_date_time.iso8601 }}"
        status_code: [200, 204]

    - name: 若有任何主機失敗，則將整個 Playbook 標記為失敗
      when: problem_hosts | length > 0
      run_once: true
      ansible.builtin.fail:
        msg: "共有 {{ problem_hosts | length }} 台主機更新失敗或無法連線：{{ problem_hosts | join(', ') }}"