- hosts: all
  become: yes
  become_user: root
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
  gather_facts: yes

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Ansible apt to install multiple packages
      register: updatesys
      apt:
        update_cache: yes
        name:
          - snmp
          - libsasl2-modules
          - qemu-guest-agent
        state: present
        
    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Ansible apt autoremove packages
      apt:
        autoremove: yes
        
    # 判斷主機狀態（移除多餘空格）
    - name: 判斷主機狀態
      set_fact:
        host_status: >-
          {% if update_result.unreachable is defined and update_result.unreachable %}unreachable{% elif upgrade_result.unreachable is defined and upgrade_result.unreachable %}unreachable{% elif update_result.failed is defined and update_result.failed %}failed{% elif upgrade_result.failed is defined and upgrade_result.failed %}failed{% else %}success{% endif %}

    # 記錄狀態（注意：使用 trim 移除空格）
    - name: 記錄主機狀態到檔案
      lineinfile:
        path: /tmp/ansible_run_status.txt
        line: "{{ ansible_date_time.iso8601 }}|{{ inventory_hostname }}|{{ host_status | trim }}"
        create: yes
      delegate_to: localhost
      become: no

- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
  
  roles:
    - role: update_notifier
      vars:
        notification_title: "Proxmox"