- hosts: all
  become: yes
  become_user: root
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
  gather_facts: yes

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      register: update_result
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600

    - name: Ansible apt to install multiple packages
      register: install_result
      apt:
        update_cache: yes
        name:
          - snmp
          - libsasl2-modules
          - qemu-guest-agent
        state: present
        
    - name: Upgrade all packages on servers
      register: upgrade_result
      apt: 
        upgrade: dist 
        force_apt_get: yes

    - name: Ansible apt autoremove packages
      register: autoremove_result
      apt:
        autoremove: yes
        
    # 判斷主機狀態
    - name: 判斷主機狀態
      set_fact:
        host_status: >-
          {% if update_result.failed | default(false) or 
                install_result.failed | default(false) or 
                upgrade_result.failed | default(false) or 
                autoremove_result.failed | default(false) %}failed{% else %}success{% endif %}

    # 記錄狀態
    - name: 記錄主機狀態到檔案
      lineinfile:
        path: /tmp/ansible_run_status.txt
        line: "{{ ansible_date_time.iso8601 }}|{{ inventory_hostname }}|{{ host_status | trim }}"
        create: yes
      delegate_to: localhost
      become: no
      throttle: 1

- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    discord_webhook: "{{ discord_webhook_url }}"
  
  roles:
    - role: update_notifier
      vars:
        notification_title: "Proxmox"